apiVersion: v1
kind: ServiceAccount
metadata:
  name: placement-controller
  namespace: ao-instances
  labels:
    app.kubernetes.io/part-of: agent-orchestrator
    agentorchestrator.io/component: placement-controller
